language: python

python:
  - 3.8

services:
 postgresql
addons:
 postgresql: '9.5'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=conline

after_success:
  - pipenv run codecov